export const routePaths = {
  DASHBOARD: '/',
  PATIENTS: '/patients',
  ADD_PATIENTS: '/patients/add',
  BULK_ADD_PATIENTS: '/patients/add/bulk',
  PATIENTS_RECEIPT_GENERATE: '/patients-receipt-generate',
  OLD_PATIENTS_RECEIPT_GENERATE: '/old-patients-receipt-generate',
  PATIENT_HISTORY: '/patient-history',
  TOKEN: '/token-receipt-generate',
  APPOINTMENTS: '/appointments',
  DEPARTMENTS: '/department',
  ADD_DEPARTMENT: '/department/add',
  BULK_ADD_DEPARTMENT: '/department/add/bulk',
  EDIT_DEPARTMENT: '/department/edit',
  PROCEDURE: '/procedure',
  ADD_PROCEDURE: '/procedure/add',
  BULK_ADD_PROCEDURE: '/procedure/add/bulk',
  EDIT_PROCEDURE: '/procedure/edit',
  VIEW_PROCEDURE: '/view-procedure',
  DOCTORS: '/doctor',
  ADD_DOCTOR: '/doctor/add',
  BULK_ADD_DOCTOR: '/doctor/add/bulk',
  EDIT_DOCTOR: '/doctor/edit',
  VIEW_DOCTOR: '/view-doctor',
  DOCTOR_FEE: '/doctor-fee',
  ADD_DOCTOR_FEE: '/doctor-fee/add',
  BULK_ADD_DOCTOR_FEE: '/doctor-fee/add/bulk',
  EDIT_DOCTOR_FEE: '/doctor-fee/edit',
  LAB: '/lab',
  ADD_LAB: '/lab/add',
  EDIT_LAB: '/lab/edit',
  WELFARE_MANAGEMENT:'welfare-management',
  ADD_WELFARE_MANAGEMENT:'/welfare-management/add',
  BILLING: '/billing',
  VITALS: '/vitals',
  CONSULTATION: '/consultation',
  PHARMACY: '/pharmacy',
  LABORATORY: '/laboratory',
  INVENTORY: '/inventory',
  REPORTS: '/reports',
  REPORTS_DAILY_VISITS: '/reports/daily-visits',
  REPORTS_BILLING: '/reports/billing',
  REPORTS_DOCTOR_WISE: '/reports/doctor-wise',
  REPORTS_DEPARTMENT_WISE: '/reports/department-wise',
  REPORTS_PHARMACY: '/reports/pharmacy',
  REPORTS_LAB: '/reports/lab',
  USERS_MANAGEMENT: '/user-management',
  ROLE_MANAGEMENT: '/role-management',
  PERMISSION_MANAGEMENT: '/permission-management',
  CREATE_PERMISSION: '/permission-management/add',
  CREATE_USER: '/user-management/create',
  SETTINGS: '/settings',
  FINANCE_REPORT: '/finance-report',
  PATIENT_REPORT: '/patient-report',
  //Pharmacy
  PRODUCT:'/product',
  ADD_PRODUCT:'/product/add',
  
  SUPPLIER:'/supplier',
  ADD_SUPPLIER:'/supplier/add',
  EDIT_SUPPLIER:'/supplier',
  BRAND:'/brand',
  ADD_BRAND:'/brand/add',
  ADD_INVOICE:'/invoice/add',
  STOCK:'/stock',
  SALE_INVOICE:'/sale-invoice',
  SALE_RETURN:'/sale-return',
  CATEGORY:'/category',
  ADD_CATEGORY:'/category/add',
  SUB_CATEGORY:'/sub-category',
  ADD_SUB_CATEGORY:'/sub-category/add',
  PACKING_TYPE:'/packing-type',
  ADD_PACKING_TYPE:'/packing-type/add',
  EDIT_PACKING_TYPE:'/packing-type/edit',
  INDENT:'/indent',
  ADD_INDENT:'/indent/add',
  PURCHASE_ORDER:'/purchase-order',
  ADD_PURCHASE_ORDER:'/purchase-order/add',
  PURCHASE_ORDER_APPROVEL:'/purchase-order-approvel',
  SEND_TO_SUPPLIER:'/send-to-supplier',
  ACCOUNTS_PO_APPROVEL:'/accounts-po-approvel',
  ACCOUNTS_PO_LIST:'/accounts-po-list',
  GRN:'/grn',
  ADD_GRN:'/grn/add',
  UNIT:'/unit',
  ADD_UNIT:'/unit/add',
  EDIT_UNIT:'/unit/edit',
  GENERIC_NAME:'/generic-name',
  ADD_GENERIC_NAME:'/generic-name/add',
  EDIT_GENERIC_NAME:'/generic-name/edit',
  DOSAGE_FORM:'/dosage-form',
  ADD_DOSAGE_FORM:'/dosage-form/add',
  ORGANIZATION:'/organization',
  ADD_ORGANIZATION:'/organization/add',
  EDIT_ORGANIZATION:'/organization/edit',
  ADD_VITALS:'/vitals/add',
  SALE_REPORT:'/sale-report'
} as const
