export const routePaths = {
  DASHBOARD: "/",
  NEW_PATIENTS: "/patients/new",
  FIND_PATIENT: "/patients/search",
  APPOINTMENTS: "/appointments",
  DEPARTMENTS: "/departments",
  ADD_DEPARTMENT:"/add-department",
  EDIT_DEPARTMENT:"/edit-department",
  PROCEDURE:"/procedure",
  ADD_PROCEDURE:"/add-procedure",
  EDIT_PROCEDURE:"/edit-procedure",
  VIEW_PROCEDURE:"/view-procedure",
  DOCTORS: "/doctors",
  ADD_DOCTOR:"/add-doctor",
  EDIT_DOCTOR:"/edit-doctor",
  VIEW_DOCTOR:"/view-doctor",
  BILLING: "/billing",
  VITALS: "/vitals",
  CONSULTATION: "/consultation",
  PHARMACY: "/pharmacy",
  LABORATORY: "/laboratory",
  INVENTORY: "/inventory",
  REPORTS: "/reports",
  REPORTS_DAILY_VISITS: "/reports/daily-visits",
  REPORTS_BILLING: "/reports/billing",
  REPORTS_DOCTOR_WISE: "/reports/doctor-wise",
  REPORTS_DEPARTMENT_WISE: "/reports/department-wise",
  REPORTS_PHARMACY: "/reports/pharmacy",
  REPORTS_LAB: "/reports/lab",
  USERS: "/users",
  SETTINGS: "/settings",
} as const;
