export const routePaths = {
  DASHBOARD: '/',
  PATIENTS: '/patients',
  ADD_PATIENTS: '/patients/add',
  PATIENTS_RECEIPT_GENERATE: '/patients-receipt-generate',
  OLD_PATIENTS_RECEIPT_GENERATE: '/old-patients-receipt-generate',
  PATIENT_HISTORY: '/patient-history',
  TOKEN: '/token-receipt-generate',
  APPOINTMENTS: '/appointments',
  DEPARTMENTS: '/department',
  ADD_DEPARTMENT: '/department/add',
  EDIT_DEPARTMENT: '/department/edit',
  PROCEDURE: '/procedure',
  ADD_PROCEDURE: '/procedure/add',
  EDIT_PROCEDURE: '/procedure/edit',
  VIEW_PROCEDURE: '/view-procedure',
  DOCTORS: '/doctor',
  ADD_DOCTOR: '/doctor/add',
  EDIT_DOCTOR: '/doctor/edit',
  VIEW_DOCTOR: '/view-doctor',
  DOCTOR_FEE: '/doctor-fee',
  ADD_DOCTOR_FEE: '/doctor-fee/add',
  EDIT_DOCTOR_FEE: '/doctor-fee/edit',
  LAB_FEE: '/lab-fee',
  ADD_LAB_FEE: '/lab-fee/add',
  EDIT_LAB_FEE: '/lab-fee/edit',
  WELFARE_MANAGEMENT:'welfare-management',
  ADD_WELFARE_MANAGEMENT:'/welfare-management/add',
  BILLING: '/billing',
  VITALS: '/vitals',
  CONSULTATION: '/consultation',
  PHARMACY: '/pharmacy',
  LABORATORY: '/laboratory',
  INVENTORY: '/inventory',
  REPORTS: '/reports',
  REPORTS_DAILY_VISITS: '/reports/daily-visits',
  REPORTS_BILLING: '/reports/billing',
  REPORTS_DOCTOR_WISE: '/reports/doctor-wise',
  REPORTS_DEPARTMENT_WISE: '/reports/department-wise',
  REPORTS_PHARMACY: '/reports/pharmacy',
  REPORTS_LAB: '/reports/lab',
  USERS_MANAGEMENT: '/user-management',
  CREATE_USER: '/user-management/create',
  SETTINGS: '/settings',
  FINANCE_REPORT: '/finance-report',
  PATIENT_REPORT: '/patient-report',
  //Pharmacy
  MEDICINE:'/medicine',
  ADD_MEDICINE:'/medicine/add',
  
  DISTRIBUTOR:'/distributor',
  ADD_DISTRIBUTOR:'/distributor/add',
  EDIT_DISTRIBUTOR:'/distributor',
  COMPANY:'/company',
  ADD_COMPANY:'/company/add',
  ADD_INVOICE:'/invoice/add',
  STOCK:'/stock',
  SALE_INVOICE:'/sale-invoice',
  CATEGORY:'/category',
  ADD_CATEGORY:'/category/add',
  DOSAGE_FORM:'/dosage-form',
  ADD_DOSAGE_FORM:'/dosage-form/add',
  INDENT:'/indent',
  ADD_INDENT:'/indent/add',
  PURCHASE_ORDER:'/purchase-order',
  ADD_PURCHASE_ORDER:'/purchase-order/add',
  PURCHASE_ORDER_APPROVEL:'/purchase-order-approvel',
  ACCOUNTS_PO_APPROVEL:'/accounts-po-approvel',
  ACCOUNTS_PO_LIST:'/accounts-po-list',
  GRN:'/grn',
  ADD_GRN:'/grn/add',
  UNIT:'/unit',
  ADD_UNIT:'/unit/add',
  EDIT_UNIT:'/unit/edit',
  GENERIC_NAME:'/generic-name',
  ADD_GENERIC_NAME:'/generic-name/add',
  EDIT_GENERIC_NAME:'/generic-name/edit',
} as const
